events {}

http {
	server {
		listen 4001;

		include /etc/nginx/mime.types;
		default_type application/octet-stream;

		root /var/www/html;
		index index.html;

		location / {
			try_files $uri /index.html;
		}
	}
}